#### Importing NumPy and Pandas libraries

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#### Reading the dataset into a 'df' variable and giving column headers as well

In [2]:
df = pd.read_csv("imports-85.csv",names = ['Symbolling','NormalizedLosses','Make','FuelType','Aspiration','NumDoors','BodyStyle','DriveWheels','EngineLocation','WheelBase','Length','Width','Height','CurbWeight','EngineType','NumCylinders','EngineSize','FuelSystem','Bore','Stroke','CompressionRatio','HorsePower','PeakRPM','CityMPG','HighWayMPG','Price'])

#### Checking head data items

In [3]:
df.head()

,Symbolling,NormalizedLosses,Make,FuelType,Aspiration,NumDoors,BodyStyle,DriveWheels,EngineLocation,WheelBase,Length,Width,Height,CurbWeight,EngineType,NumCylinders,EngineSize,FuelSystem,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG,Price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

#### Checking tail data items

In [4]:
df.tail()

,Symbolling,NormalizedLosses,Make,FuelType,Aspiration,NumDoors,BodyStyle,DriveWheels,EngineLocation,WheelBase,Length,Width,Height,CurbWeight,EngineType,NumCylinders,EngineSize,FuelSystem,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG,Price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

#### Checking no. of rows and no. of columns

In [5]:
df.shape

(205, 26)

#### Checking dataset information about column data type and no. of non-null entries

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Symbolling        205 non-null    int64
 1   NormalizedLosses  205 non-null    object
 2   Make              205 non-null    object
 3   FuelType          205 non-null    object
 4   Aspiration        205 non-null    object
 5   NumDoors          205 non-null    object
 6   BodyStyle         205 non-null    object
 7   DriveWheels       205 non-null    object
 8   EngineLocation    205 non-null    object
 9   WheelBase         205 non-null    float64
 10  Length            205 non-null    float64
 11  Width             205 non-null    float64
 12  Height            205 non-null    float64
 13  CurbWeight        205 non-null    int64
 14  EngineType        205 non-null    object
 15  NumCylinders      205 non-null    object
 16  EngineSize        205 non-null    int64
 17  FuelSystem        205 non-null    object
 18  Bore              205 non-null    object
 19  Stroke            205 non-null    object
 20  CompressionRatio  205 non-null    float64
 21  HorsePower        205 non-null    object
 22  PeakRPM           205 non-null    object
 23  CityMPG           205 non-null    int64
 24  HighWayMPG        205 non-null    int64
 25  Price             205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

#### Calculating statistical measures for numerical columns

In [7]:
df.describe()

,Symbolling,WheelBase,Length,Width,Height,CurbWeight,EngineSize,CompressionRatio,CityMPG,HighWayMPG
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

#### Checking number of null values

In [8]:
df.isnull().sum()

Symbolling          0
NormalizedLosses    0
Make                0
FuelType            0
Aspiration          0
NumDoors            0
BodyStyle           0
DriveWheels         0
EngineLocation      0
WheelBase           0
Length              0
Width               0
Height              0
CurbWeight          0
EngineType          0
NumCylinders        0
EngineSize          0
FuelSystem          0
Bore                0
Stroke              0
CompressionRatio    0
HorsePower          0
PeakRPM             0
CityMPG             0
HighWayMPG          0
Price               0
dtype: int64

#### The dataset has '?' as a placeholder for null values. We will replace it with np.NaN

In [9]:
df.replace(to_replace = '?', value = np.NaN, inplace = True)

#### Checking dataset after replacement

In [10]:
df.head(10)

,Symbolling,NormalizedLosses,Make,FuelType,Aspiration,NumDoors,BodyStyle,DriveWheels,EngineLocation,WheelBase,Length,Width,Height,CurbWeight,EngineType,NumCylinders,EngineSize,FuelSystem,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG,Price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN

#### Calculating null values after replacement

In [11]:
df.isnull().sum()

Symbolling           0
NormalizedLosses    41
Make                 0
FuelType             0
Aspiration           0
NumDoors             2
BodyStyle            0
DriveWheels          0
EngineLocation       0
WheelBase            0
Length               0
Width                0
Height               0
CurbWeight           0
EngineType           0
NumCylinders         0
EngineSize           0
FuelSystem           0
Bore                 4
Stroke               4
CompressionRatio     0
HorsePower           2
PeakRPM              2
CityMPG              0
HighWayMPG           0
Price                4
dtype: int64

#### Replaced null values with mean for column 'NormalizedLosses'

In [12]:
df['NormalizedLosses'] = df['NormalizedLosses'].astype('float')

In [13]:
df['NormalizedLosses'].fillna(122,inplace = True)

In [14]:
df.isnull().sum()

Symbolling          0
NormalizedLosses    0
Make                0
FuelType            0
Aspiration          0
NumDoors            2
BodyStyle           0
DriveWheels         0
EngineLocation      0
WheelBase           0
Length              0
Width               0
Height              0
CurbWeight          0
EngineType          0
NumCylinders        0
EngineSize          0
FuelSystem          0
Bore                4
Stroke              4
CompressionRatio    0
HorsePower          2
PeakRPM             2
CityMPG             0
HighWayMPG          0
Price               4
dtype: int64

#### Replaced null values for columns 'bore','stroke','HorsePower' and 'PeakRPM' with respectvie mean

In [15]:
temp_list = ['Bore', 'Stroke', 'HorsePower', 'PeakRPM']
for colName in temp_list:
    # converting columns to float dtype
    df[colName] = df[colName].astype('float')
    
    # filling nan values with mean
    df[colName].fillna(df[colName].mean(), inplace = True)

df.describe()

,Symbolling,NormalizedLosses,WheelBase,Length,Width,Height,CurbWeight,EngineSize,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,122.000000,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329751,3.255423,10.142537,104.256158,5125.369458,25.219512,30.751220
std,1.245307,31.681008,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.519211,476.979093,6.542142,6.886443
min,-2.000000,65.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000
25%,0.000000,101.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000
50%,1.000000,122.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000
75%,2.000000,137.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000
max,3.000000,256.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000

In [16]:
df.isnull().sum()

Symbolling          0
NormalizedLosses    0
Make                0
FuelType            0
Aspiration          0
NumDoors            2
BodyStyle           0
DriveWheels         0
EngineLocation      0
WheelBase           0
Length              0
Width               0
Height              0
CurbWeight          0
EngineType          0
NumCylinders        0
EngineSize          0
FuelSystem          0
Bore                0
Stroke              0
CompressionRatio    0
HorsePower          0
PeakRPM             0
CityMPG             0
HighWayMPG          0
Price               4
dtype: int64

#### Replaced null values in column 'NumDoors' with highest freqency entry i.e four

In [17]:
df['NumDoors'].fillna('four',inplace = True)
df.isnull().sum()

Symbolling          0
NormalizedLosses    0
Make                0
FuelType            0
Aspiration          0
NumDoors            0
BodyStyle           0
DriveWheels         0
EngineLocation      0
WheelBase           0
Length              0
Width               0
Height              0
CurbWeight          0
EngineType          0
NumCylinders        0
EngineSize          0
FuelSystem          0
Bore                0
Stroke              0
CompressionRatio    0
HorsePower          0
PeakRPM             0
CityMPG             0
HighWayMPG          0
Price               4
dtype: int64

#### Dropping null entries in Price column as Price is target variable and it shouldnt have null values

In [18]:
df.dropna(subset = ['Price'],inplace = True)
df['Price'] = df['Price'].astype('float')

#### Adding new columns for city-L/100km and highway=L/100km

In [19]:
def convert(colName):
    for i in df[colName]:
        df.loc[df[colName]==i,colName + '_L/100Km'] = 235 / i

In [20]:
convert('CityMPG')
convert('HighWayMPG')

In [21]:
df.head(10)

,Symbolling,NormalizedLosses,Make,FuelType,Aspiration,NumDoors,BodyStyle,DriveWheels,EngineLocation,WheelBase,Length,Width,Height,CurbWeight,EngineType,NumCylinders,EngineSize,FuelSystem,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG,Price,CityMPG_L/100Km,HighWayMPG_L/100Km
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,8.703704
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,8.703704
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,9.038462
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,7.833333
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,10.681818
5,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0,12.368421,9.400000
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0,12.368421,9.400000
7,1,122.0,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,18920.0,12.368421,9.400000
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0,13.823529,11.750000
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0,10.217391,8.103448

In [84]:
df.rename(columns = {'CityMPG_L/100Km':'City_L/100km', 'HighWayMPG_L/100Km':'Highway_L/100Km'}, inplace = True)

#### Normalizing the columns 'Length', 'Width', 'Height'

In [85]:
for col in ['Length', 'Width', 'Height']:
    m1 = df[col].max()
    df[col] = df[col]/m1
    
df.head()

,Symbolling,NormalizedLosses,Make,FuelType,Aspiration,NumDoors,BodyStyle,DriveWheels,EngineLocation,WheelBase,Length,Width,Height,CurbWeight,EngineType,NumCylinders,EngineSize,FuelSystem,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG,Price,City_L/100km,Highway_L/100Km
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.811148,0.890278,0.816054,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,8.703704
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.811148,0.890278,0.816054,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,8.703704
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,0.822681,0.909722,0.876254,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,9.038462
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,0.848630,0.919444,0.908027,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,7.833333
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,0.848630,0.922222,0.908027,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,10.681818

#### Encoding -> Converting categorical data to numeric

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()

In [26]:
df[df.select_dtypes(include = ['object']).columns] = df[df.select_dtypes(include = ['object']).columns].apply(le.fit_transform)

#### Final dataset

In [27]:
df.head(10)

,Symbolling,NormalizedLosses,Make,FuelType,Aspiration,NumDoors,BodyStyle,DriveWheels,EngineLocation,WheelBase,Length,Width,Height,CurbWeight,EngineType,NumCylinders,EngineSize,FuelSystem,Bore,Stroke,CompressionRatio,HorsePower,PeakRPM,CityMPG,HighWayMPG,Price,CityMPG_L/100Km,HighWayMPG_L/100Km
0,3,122.0,0,1,0,1,0,2,0,88.6,168.8,64.1,48.8,2548,0,2,130,5,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,8.703704
1,3,122.0,0,1,0,1,0,2,0,88.6,168.8,64.1,48.8,2548,0,2,130,5,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,8.703704
2,1,122.0,0,1,0,1,2,2,0,94.5,171.2,65.5,52.4,2823,4,3,152,5,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,9.038462
3,2,164.0,1,1,0,0,3,1,0,99.8,176.6,66.2,54.3,2337,2,2,109,5,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,7.833333
4,2,164.0,1,1,0,0,3,0,0,99.4,176.6,66.4,54.3,2824,2,1,136,5,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,10.681818
5,2,122.0,1,1,0,1,3,1,0,99.8,177.3,66.3,53.1,2507,2,1,136,5,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0,12.368421,9.400000
6,1,158.0,1,1,0,0,3,1,0,105.8,192.7,71.4,55.7,2844,2,1,136,5,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0,12.368421,9.400000
7,1,122.0,1,1,0,0,4,1,0,105.8,192.7,71.4,55.7,2954,2,1,136,5,3.19,3.40,8.5,110.0,5500.0,19,25,18920.0,12.368421,9.400000
8,1,158.0,1,1,1,0,3,1,0,105.8,192.7,71.4,55.9,3086,2,1,131,5,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0,13.823529,11.750000
10,2,192.0,2,1,0,1,3,2,0,101.2,176.8,64.8,54.3,2395,2,2,108,5,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0,10.217391,8.103448